# Generated by Django 3.2 on 2021-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoModel',
            fields=[
                ('alumnoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('alumnoNombre', models.CharField(db_column='nombres', help_text='Ingrese el nombre', max_length=100, verbose_name='Nombres')),
                ('alumnoApePaterno', models.CharField(db_column='apePat', help_text='Ingrese el apellido paterno', max_length=100, verbose_name='Apellidos')),
                ('alumnoApeMaterno', models.CharField(db_column='apeMat', help_text='Ingrese el apellido materno', max_length=100, verbose_name='Apellido Materno')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'db_table': 'alumno',
            },
        ),
    ]
