# Generated by Django 3.2 on 2021-04-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mant', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaModel',
            fields=[
                ('matriculaId', models.AutoField(db_column='idMatricula', primary_key=True, serialize=False, unique=True)),
                ('matriculaPeriodo', models.CharField(db_column='periodo', help_text='Ingrese el periodo', max_length=10, verbose_name='Periodo')),
                ('alumno', models.ForeignKey(db_column='idAlumno', help_text='Alumno', on_delete=django.db.models.deletion.CASCADE, related_name='alumnoMatricula', to='mant.alumnomodel', verbose_name='alumno')),
            ],
            options={
                'verbose_name': 'matricula',
                'db_table': 'matricula',
            },
        ),
    ]
